# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Haru_read' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Haru_read

  pod 'AudioKit'

  target 'Haru_readTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Haru_readUITests' do
    # Pods for testing
  end

end
